### ISSUE TITLE
Orbit types and representative preview images for KerrGeoOrbitFunction

### ISSUE THREAD

**Issue by nielsw2** [BlackHolePerturbationToolkit/KerrGeodesics#18]
As we are starting to add more types of orbit we maybe each KerrGeoOrbitFunction should store a Type of orbit so that, `orbit["Type"]` would return, i.e.,

{"Timelike", {"Bound", {"Spherical"}}}
{"Timelike", {"Bound", {"Eccentric", "Equatorial"}}}
{"Timelike, "Hyperbolic"}
{"Null", "Hyperbolic"}

Once the orbits are classified like this we could use a representive image for the preview of the KerrGeoOrbitFunction, rather than rendering the particular orbit. The preview is small so I'm not sure there is much value in rendering a precise preview. Furthermore, if you compute the trajectory using the analytic formula they are slow to evaluate along the orbit so the rendering takes a lot of time. Instead we could just show an circular, eccentric, spherical, generic, hyperbolic, etc orbit that matches the type above.

**Comment by barrywardell** [comment]
I have code to make the preview images much simpler, essentially doing what you say and showing representations of the type of orbit. It still needs to be tidied up, which I why I didn't commit it yet.

**Comment by barrywardell** [comment]
It would be worth thinking carefully about exactly what the returned format should be, i.e. should it be nested lists or should it be flattened, or should it be something else (e.g. an association)?

**Comment by barrywardell** [comment]
This was fixed in ae1e6569
