### ISSUE TITLE
Some functions not available when indirectly loading package

### ISSUE THREAD

**Issue by barrywardell** [BlackHolePerturbationToolkit/KerrGeodesics#23]
Many functions (including KerrGeoSeparatrix, for example) are not available when the KerrGeodesics are indirectly loaded while loading another package.

**Comment by VisakanBalakumar** [comment]
Hi Barry, I've encountered this. Do you know how would one load the KerrGeodesics package directly to circumvent this problem?

**Comment by MvdMeent** [comment]
@VisakanBalakumar 

<<KerrGeodesics`

**Comment by nielsw2** [comment]
This issue occurs because the other packages in the Toolkit, e.g., Teukolsky, do not load the entire KerrGeodesics package. They just load the subpackages they require. We are probably going to change this so in future packages that depend on KerrGeodesics will load the whole package.

**Comment by VisakanBalakumar** [comment]
Thanks for the help!
