### ISSUE TITLE
KerrGeoOrbit and KerrGeoSeparatrix marked red

### ISSUE THREAD

**Issue by fieldequation** [BlackHolePerturbationToolkit/KerrGeodesics#24]
Hi,

While I'm using KerrGeoOrbit and KerrGeoSeparatrix, these two functions are displayed in red and indicate the following error.

<img width="669" alt="Screen Shot 2022-04-30 at 17 28 24" src="https://user-images.githubusercontent.com/99890202/166100072-feb695cd-f6b5-44a1-92e8-ed5d8fb65adf.png">

**Comment by nielsw2** [comment]
Hi, 

This implies the symbol has been defined more than once. Do you load any other packages from the Toolkit or make use of the KerrGeoOrbit or KerrGeoSeparatrix function before the KerrGeodesics package is loaded?

If possible, could you provide a short notebook where the issue happens?

Niels

**Comment by fieldequation** [comment]
Hi,
Sorry for replying late. Fortunately, when I restarted the kernel, both functions worked properly without issues. I will set this issue to close later.
