### ISSUE TITLE
Tetrad problems in KerrGeodesicis`ParallelTransport

### ISSUE THREAD

**Issue by angelbeatsss** [BlackHolePerturbationToolkit/KerrGeodesics#25]
The code int he KerrGeodeiscs`ParallelTransport` subpackage is an implementation of the results presented in arXiv:1906.05090.

The definition for tetrad e3 in code tetrad may be different from the definition of tetrad e3 in arXiv:1906.05090.
There will be a Sin[theta] factor missing
![test](https://user-images.githubusercontent.com/37038932/179885289-059fbcee-8771-4981-bff5-c1a89d0e2841.PNG)
.

**Comment by nielsw2** [comment]
Thanks for reporting this. @MvdMeent wrote this subpackage so perhaps he can comment on the discrepancy.

**Comment by MvdMeent** [comment]
Note that arXiv:1906.05090 uses modified Boyer-Lindquist coordinates using z=cos[theta] as a coordinate, whereas the toolkit implementation uses standard Boyer-Lindquist coordinates. The difference is exactly a factor -sin[theta] on the third component of any vector.

Once you correct for this the expressions should agree. Let me know, if you find that they still don't.

**Comment by angelbeatsss** [comment]
Well, thanks. 
Once I add this factor -sin[theta], the expressions agree.

**Comment by angelbeatsss** [comment]
Well, thanks. 
Once I add this factor -sin[theta], the expressions agree.
