### ISSUE TITLE
KerrGeoBoundOrbitQ

### ISSUE THREAD

**Issue by MvdMeent** [BlackHolePerturbationToolkit/KerrGeodesics#33]
1) Could we do something like this to this:

```
KerrGeoBoundOrbitQ[a_?NumericQ, p_?NumericQ, e_?NumericQ, 
  x_?NumericQ] := Module[{En, L, Q, r1, r2, r3, r4},
  {En, L, Q} = Values@KerrGeoConstantsOfMotion[a, p, e, x];
  If[
   Not[And @@ (PossibleZeroQ /@ Im@{En, L, Q}) ],
   Return[False],
   {r1, r2, r3, r4} = 
    KerrGeodesics`OrbitalFrequencies`Private`KerrGeoRadialRoots[a, p, 
     e, x, En, Q];
   	If[r2 >= r3, True, False, False],
        False
   ]
  ]
```
instead of the current implementation?

This should generally be faster, and does not depend on a potentially fragile numerical RootFind.

2) Should we rename this function? It is testing whether we might be dealing with a plunging orbit, but currently does not test for the possibility of a scattering orbit (e>=1)

**Comment by nielsw2** [comment]
I think this change looks good and should certainly be faster. Rather than changing the function name we could instead also check if e < 1, especially if we are planning to add commands like `KerrGeoScatteredOrbitQ`

**Comment by nielsw2** [comment]
At the moment I have disabled this function. We were planning to have `KerrGeoScatteredOrbitQ` and `KerrGeoPlungeOrbitQ` as well but after some discussion we realized a much larger classification is needed (marginally bound, marginally stable).

For now best use `KerrGeoOrbitType` and examine the list to classify an orbit.

As the function is disabled I will close this issue for now.
