### ISSUE TITLE
Replacing Print[] with Message[]

### ISSUE THREAD

**Issue by VojtechW** [BlackHolePerturbationToolkit/KerrGeodesics#39]
Error statements and messages about function evaluations are currently mostly returned to the user through `Print[]`. This means that they cannot be turned off (note even with `Quiet` I believe). Should one instead use [Message[]](https://reference.wolfram.com/language/ref/Message.html) to provide a more standardized (and customizable) messaging interface for the package?

**Comment by nielsw2** [comment]
We should use `Message[]` instead of `Print[]`. The print functions to be replaced are in the `KerrGeoOrbit.m`, `FourVelocity.m` and `ParallelTransport.m` files

**Comment by nielsw2** [comment]
This has been fixed with pull request #48
