### ISSUE TITLE
1/0 in KerrGeoOrbit when below ISCO

### ISSUE THREAD

**Issue by Patrick-Bourg** [BlackHolePerturbationToolkit/KerrGeodesics#47]
I obtain 1/0 warning messages when calculating KerrGeoOrbit[a,p,e,1] for a=e=0, and certain values of p<6 M.

Tested it for p=6,4 (which has even more warning messages) and seemingly any value between 3M and 4M.
p=5 or non integer values between (4,6) do not issue any such messages.

**Comment by MvdMeent** [comment]
What happens when you specify Method->"Analytic"?

**Comment by Patrick-Bourg** [comment]
I tried: KerrGeoOrbit[a, p, e, 1, Method -> "Analytic"], but I obtain the same results.

**Comment by nielsw2** [comment]
This has now been fixed in the master branch following the merge of pull request #29. I will close this issue.
