### ISSUE TITLE
Typo in test name in KerrGeoFrequencies.wlt

### ISSUE THREAD

**Issue by samdupton** [BlackHolePerturbationToolkit/KerrGeodesics#6]
The test name title for "KerrGeoFrequencies generic" is given as "SpinWeightedSpheroidalEigenvalue".

https://github.com/BlackHolePerturbationToolkit/KerrGeodesics/blob/db5d097fa23682a4d8bd411c577f456beb30c387/Tests/KerrGeoFrequencies.wlt#L2

**Comment by samdupton** [comment]
Fixed in 2a9190756ae376583b353a6680be7605986081c4 from https://github.com/BlackHolePerturbationToolkit/KerrGeodesics/pull/5.

**Comment by nielsw2** [comment]
Thanks for the bug report. The correction has now been merged into the master branch.
