### ISSUE TITLE
Parametrization wrt Darwin

### ISSUE THREAD

**Issue by bbonga** [BlackHolePerturbationToolkit/KerrGeodesics#8]
In the example notebook file "KerrGeodesics.nb", there is a section dedicated to equitorial orbits.
The option Parametrization in KerrGeoOrbit does not work.

**Comment by nielsw2** [comment]
Thanks for the feedback. This bug was introduced after a recent refactorization of the code following the recent BHPToolkit meeting. It is now fixed so please test the updated code.
